name: space_app
description: "Explore the planets of the solar system in 3D."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  interactive_3d: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/env/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Variable.ttf
    - family: Space Grotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Variable.ttf
